################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
main.obj: ../main.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib -me --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/common" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/portable/MemMang" --include_path="C:/ti/CC3200SDK_1.3.0/cc3200-sdk/simplelink_extlib/provisioninglib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink/include" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/driverlib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/driverlib/inc" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink/source" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/include" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/portable/CCS/ARM_CM3" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/oslib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/Drone_Project" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --define=cc3200 --define=USE_FREERTOS --define=SL_PLATFORM_MULTI_THREADED --define=ccs -g --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="main.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

network_common.obj: ../network_common.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib -me --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/common" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/portable/MemMang" --include_path="C:/ti/CC3200SDK_1.3.0/cc3200-sdk/simplelink_extlib/provisioninglib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink/include" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/driverlib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/driverlib/inc" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink/source" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/include" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/portable/CCS/ARM_CM3" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/oslib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/Drone_Project" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --define=cc3200 --define=USE_FREERTOS --define=SL_PLATFORM_MULTI_THREADED --define=ccs -g --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="network_common.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

pinmux.obj: ../pinmux.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib -me --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/common" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/portable/MemMang" --include_path="C:/ti/CC3200SDK_1.3.0/cc3200-sdk/simplelink_extlib/provisioninglib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink/include" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/driverlib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/driverlib/inc" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink/source" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/include" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/portable/CCS/ARM_CM3" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/oslib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/Drone_Project" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --define=cc3200 --define=USE_FREERTOS --define=SL_PLATFORM_MULTI_THREADED --define=ccs -g --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="pinmux.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

startup_ccs.obj: ../startup_ccs.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib -me --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/common" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/portable/MemMang" --include_path="C:/ti/CC3200SDK_1.3.0/cc3200-sdk/simplelink_extlib/provisioninglib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink/include" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/driverlib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/driverlib/inc" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink/source" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/include" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/portable/CCS/ARM_CM3" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/oslib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/Drone_Project" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --define=cc3200 --define=USE_FREERTOS --define=SL_PLATFORM_MULTI_THREADED --define=ccs -g --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="startup_ccs.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

uart_if.obj: ../uart_if.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib -me --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/common" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/portable/MemMang" --include_path="C:/ti/CC3200SDK_1.3.0/cc3200-sdk/simplelink_extlib/provisioninglib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink/include" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/driverlib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/driverlib/inc" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink/source" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/include" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/portable/CCS/ARM_CM3" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/oslib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/Drone_Project" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --define=cc3200 --define=USE_FREERTOS --define=SL_PLATFORM_MULTI_THREADED --define=ccs -g --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="uart_if.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

udma_if.obj: ../udma_if.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=vfplib -me --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/common" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/portable/MemMang" --include_path="C:/ti/CC3200SDK_1.3.0/cc3200-sdk/simplelink_extlib/provisioninglib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink/include" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/driverlib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/driverlib/inc" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/simplelink/source" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/include" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/third_party/FreeRTOS/source/portable/CCS/ARM_CM3" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/library/oslib" --include_path="C:/Users/Pierre/Workspace/TI/CC3200/Drone_Project" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --define=cc3200 --define=USE_FREERTOS --define=SL_PLATFORM_MULTI_THREADED --define=ccs -g --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="udma_if.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


